const ASSIGNMENT_GROUPS = ["Labs & Quizzes", "Projects & Assessments", "Tasks"];
export default {
  ASSIGNMENT_GROUPS,
  ASSIGNMENT_GROUPS_MAPPING: {
    lesson: ASSIGNMENT_GROUPS[0],
    project: ASSIGNMENT_GROUPS[1],
    assessment: ASSIGNMENT_GROUPS[1],
    presentation: ASSIGNMENT_GROUPS[1],
    task: ASSIGNMENT_GROUPS[2],
  },

  // Error Codes
  ERR_COURSE_NOT_CONFIRMED: "COURSE_NOT_CONFIRMED",
  ERR_OPERATION_CANCELLED: "OPERATION_CANCELLED",
  ERR_FILE_LOAD_FAILURE: "FILE_LOAD_FAILURE",
  ERR_REQUEST_FAILED: "REQUEST_FAILED",
  ERR_DUPLICATE_OPERATION: "DUPLICATE_OPERATION",
  ERR_UNIT_NUMBER_MISSING: "UNIT_NUMBER_MISSING",
};
